global:
  smtp_smarthost: 'mailserver:25'
  smtp_from: 'alertmanager@example.com'
  smtp_require_tls: false

route:
  receiver: 'email'
  # group_by: [ alertmanager ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'email'
    email_configs:
      - to: 'test@example.com'
        headers:
          subject: 'Prometheus Mail Alerts'