global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.localhost:9090']

  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['orion.server.local:3100']

alerting:
  alertmanagers:
   - scheme: http
   - static_configs:
     - targets:
        - alertmanager:9093

rule_files:
  - 'alert.rules.yml'
